### ISSUE TITLE
Dragging SVG path with ID resets position

### ISSUE THREAD

**Issue by axelboc** [rexxars/react-element-pan#11]
When I drag any other part of the SVG it works as expected, but when I drag an element (shape, group, etc.) that has a `id` attribute, the panning position jumps back to the start! This seems to happen in both Firefox and Chrome. Anyone else seeing this?

**Comment by altaudio** [comment]
We were having a similar problem. Our solution is in this PR #13

**Comment by rexxars** [comment]
#13 has been merged, sorry about this taking forever.
