### ISSUE TITLE
× TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by Thilagm** [rexxars/react-element-pan#14]
displayName: 'ElementPan',
  66 | 
  67 | propTypes: {
> 68 |     className: PropTypes.string,
  69 |     onPanStart: PropTypes.func,
  70 |     onPan: PropTypes.func,
  71 |     onPanStop: PropTypes.func,

When will it be update to react 16?

**Comment by rexxars** [comment]
React 16 now supported, sorry about taking forever.
