### ISSUE TITLE
React 16 and Typescript compatibility

### ISSUE THREAD

**Issue by only-cliches** [rexxars/react-element-pan#9]
Anyone looking to get this lib working with the newest version of React, I ported it to Typescript and removed the items in the lib conflicting with React 16.

You can grab it here: `npm install react-element-pan-ts`.

https://github.com/ClickSimply/react-element-pan

Shouldn't cause any breaking changes unless you depend on the prebuilt browser bundle.  Even though it's written in Typescript it will play nice with ES6/Babel and ES5 projects without any extra hassle.

rexxars, I'd be more than happy to submit a pull request.  Just let me know.

**Comment by rexxars** [comment]
Thanks, chief! Released 2.0 with React 16 support
